name: Create release zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release-${{ steps.date.outputs.date }}.zip'
        path: './source/bin'
    
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'release-${{ steps.date.outputs.date }}.zip'
        replacesArtifacts: false
        allowUpdates: true
        tag: release-${{ steps.date.outputs.date }}
