name: Create release zip
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        path: './source/bin'
  release:
      needs: [build]
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.zip'
          tag: release-${{ steps.date.outputs.date }}
